import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { ModalLayout } from "./modal_layout";

import "../globals.css";

interface IProps {
  children: React.ReactNode;
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: IProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <ModalLayout>{children}</ModalLayout>
        </Providers>
      </body>
    </html>
  );
}
